export const AUTHORITIES = {
  APPROVAL: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  DEPARTMENT: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  DESIGNATION: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  USER: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  HOLIDAY: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  JOB: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  LEAVEAPPLICATION: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  LEAVETYPE: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  LOCATION: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  CANDIDATE: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
  TIMESHEET: ['GET', 'CREATE', 'UPDATE', 'DELETE'],
};
